### ISSUE TITLE
Cannot stop program

### ISSUE THREAD

**Issue by KnifeFly** [tsaikd/gogstash#199]
i clone and build, and start program: 
```
./gogstash worker --config ./gogstash.yml
```

gogstash.yml config file content:
```
worker: 2
chsize: 1000

input:
  - type: file
    path: /tmp/logstash-tutorial.log
    start_position: beginning
    sincedb_write_interval: 5

output:
  - type: stdout
    codec: json
```

while i want to stop the program, so i enter `command + c` to interrupt, but seems the program cannot stop, just print `interrupt` information, i sam not sure that happen.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/13764181/202457227-9b6dc137-232c-43bd-957e-78ccd8dc1592.png">

```
util.go:116 [info] interrupt
```

machine: macos 12.5.1
go version: go version go1.18.5 darwin/amd64
