### ISSUE TITLE
Ctrl+C does not kill worker processes

### ISSUE THREAD

**Issue by Mizaro** [tsaikd/gogstash#211]
While trying the project on my local machine. I did the following:
```terminal
go run .
ps aux | grep gog
```
And noticed that the worker processes are still alive.
```
user1    5896 21.6  0.3 1628392 27444 pts/6   Sl   11:00   0:01 /tmp/go-build3520306496/b001/exe/gogstash worker
user1    5897 21.0  0.3 1628136 31328 pts/6   Sl   11:00   0:01 /tmp/go-build3520306496/b001/exe/gogstash worker
```

My config is `config.yaml` is:
```yaml
chsize: 1000
worker: 2
event:
  sort_map_keys: false
  remove_field: ['@metadata']

input:
  - type: lorem

output:
  - type: stdout
    codec: json
```
