### ISSUE TITLE
Loki and org_id

### ISSUE THREAD

**Issue by KVInventoR** [tsaikd/gogstash#226]
How can I define org_id for loki? If Loki runs in multi tenancy mode
`
2023/08/26 20:17:23 outputloki.go:177 [error] output loki  startCode: 401  error:no org id`

https://grafana.com/docs/loki/latest/operations/multi-tenancy/

```
output:
  - type: stdout
    codec: json

  - type: loki
    urls:
      - "http://IP:8080/loki/api/v1/push"
    auth: "X-Scope-OrgID:Logs"
    
```
