### ISSUE TITLE
Log sending delay

### ISSUE THREAD

**Issue by YouZhengChuan** [tsaikd/gogstash#96]
![image](https://user-images.githubusercontent.com/3882312/57602197-0ec4d880-7591-11e9-90dc-a7e256fa9c14.png)

Gostash always sends old logs. The latest logs always wait a few minutes before they start to send, and the longer gogstash runs, the longer the log delay will be, and the delay will be several days at most.

**Comment by tsaikd** [comment]
What's your input/filter/output?

**Comment by YouZhengChuan** [comment]
```yaml
input:
  - type: file
    # (required)
    path: "/home/work/log/nginx/pcdn_access.log"
    # (optional), one of ["beginning", "end"], default: "end"
    start_position: end
    # (optional), default: ".sincedb.json"
    sincedb_path: ".sincedb.json"
    # (optional), in seconds, default: 15
    sincedb_write_interval: 15

filter:
  - type: grok
    match: ["%{NGINX_ACCESS}"]
    source: "message"
    patterns_path: "configs/grok-patterns.grok"

  - type: grok
    match: ["%{NGINX_ACCESS_REQUEST}"]
    source: "rawrequest"
    patterns_path: "configs/grok-patterns.grok"

  - type: grok
    match: ["%{REQUEST_URL}"]
    source: "request_url"
    patterns_path: "configs/grok-patterns.grok"

  - type: url_param
    source: "request_param"
    prefix: "param_"

  - type: grok
    match: ["%{STATUS_N}"]
    source: "status"
    patterns_path: "configs/grok-patterns.grok"
    #patterns:

  - type: date
    format: ["02/Jan/2006:15:04:05 +0800"]
    source: time_local
    joda: false

  - type: typeconv
    conv_type: int64
    fields: ["body_bytes_sent", "status", "server_port"]

  - type: typeconv
    conv_type: float64
    fields: ["httpversion", "request_time", "upstream_response_time"]

  - type: add_field
    key: "metric"
    value: "nginx_alog"

  - type: add_field
    key: "module_name"
    value: "sd01-db5-nginx"

  - type: remove_field
    fields: ["rawrequest", "request_url", "request_param", "message"]

output:
  - type: http
    urls: ["http://10.20.0.13:8090/api/v1/log"]
  #- type: stdout
```
